---
title: "ADSProject3"
format: pdf
editor: visual
---

## Project 3: A/B Test

Author: Hanzhong Yang (hy2870) Preach Apintanapong (pa2615) Mengyan Li (ml4779) Raymond Li (jl6787)

-   **Introduction & Research Question**

    In this project, we are designing and conducting an A/B Test experiment. A/B Test plays an important role in data science, especially for decision-making and user experience optimization. The idea behind A/B Testing is you have two group–A and B, and Group A is the original version and Group B is the modified version. You are comparing how each group behaves. By comparing the outcome for Group A and Group B, you will find out which one is better for you to use.

    Research question: if red color and sales affect people's choice of buying clothes

    Motivations:

-   **Experimental Design & Methodology**

    We have two websites–Website A and Website B.

    On both websites, we have three T-shirts--Plain Black Shirt, Code Shirt, and Graphic Shirt. The Plain Black Shirt is \$100 with 25% discount. The Code Shirt is \$75. The Graphic Shirt is \$50. You have \$75 in balance to buy the T-shirt. You can buy any T-shirt. But the balance is only sufficient for you to buy one T-shirt. If you already buy one and want to buy another. The website will pop up "Insufficient funds to buy this item". The Plain Black Shirt has no figures or anything on it. But in website A, the sales button is in red and it has a sale. We design this experiment to see if red color and sales affect user click rates. The Plain Black Shirt and Code Shirt have same prices. But different marketing strategies. Graphic Shirt is cheaper and is used to be a comparison. You can also Rate the Super Graphic Store or leave comments.

    Difference between website A and website B: Website A and Website B are mainly same except that in Website A, the Plain Black Shirt has red sales button while Website B has regular blue button.

-   **Data Collection**

    We sent the two website randomly to two stats students groups and our classmates. In total, 69 students entered Website A and 57 students entered Website B. They clicked on the website and left us valuable data.

    We analyzed the data via Google Analytics. In Google Analytics–View user engagement & retention tab, we are able to download the datasets for different events such as different kinds of purchase on three T-shirts. In User Explorer, we are able to download the datasets for individual users behaviors.

<!-- -->

-   **Statistical Analysis & Results**

-   **Interpretation & Conclusion**

-   **Challenges & Limitations**

-   Contribution:

    Hanzhong Yang (hy2870): Statistical Analysis, Statistical Results, Report drafting

    Preach Apintanapong (pa2615): Formal website building, Google Analytics building, Report drafting

    Mengyan Li (ml4779): Original website building, User Explorer Building, Report drafting

    Raymond Li (jl6787): Coding for Statistical Analysis. Please add your additional work here
